compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fsdp_config: {}
mixed_precision: bf16
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
deepspeed_config:
  train_micro_batch_size_per_gpu: 4
  gradient_accumulation_steps: 1
  steps_per_print: 2000
  bf16:
    enabled: true
  zero_optimization:
    stage: 2
    overlap_comm: true
    contiguous_gradients: true
    allgather_partitions: true
    allgather_bucket_size: 200000000
    reduce_scatter: true
    reduce_bucket_size: 200000000
  optimizer:
    type: AdamW
    params:
      lr: 2e-5
      betas: [0.9, 0.999]
      eps: 1e-8
      weight_decay: "auto"
  scheduler:
    type: WarmupLR
    params:
      warmup_min_lr: 0
      warmup_max_lr: 2e-5
      warmup_num_steps: "auto"
  gradient_clipping: 1.0
  wall_clock_breakdown: false 